name: Close past-due milestones
description: Close GitHub milestones that are past-due and either empty or completed.

inputs:
  token:
    description: 'The GitHub token to use for API authentication.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'check-circle'
  color: 'green'
  name: 'Close Milestones'

permissions:
  issues: write
  pull-requests: write
